#!/bin/bash

set -eu

rename() {
  path=$1
  filename="${path%.*}"
  extension="${path##*.}"
  classname=$(basename $path .java)

  git mv $filename.java $filename.kt
  git commit -m "Rename $classname"
  mv $filename.kt $filename.java
}

donecmd() {
  path=$1
  classname=$(basename $path .kt)

  git add -u $path
  git commit -m "Kotlinize $classname"
}

version() {
  echo "j2k v0.1"
}

case $1 in
rename)
  rename $2
  ;;

done)
  donecmd $2
  ;;

version | --version | -v)
  version
  ;;
esac
