#!/bin/bash

set -eu

checkout() {
  path=$1
  classname=$(basename $path .java)
  snake_case=$(sed -e 's/\([a-z]\)\([A-Z]\)/\1_\2/g' <<< $classname | tr '[A-Z]' '[a-z]')
  git checkout -b "kotlinize_$snake_case"
}

rename() {
  path=$1
  filename="${path%.*}"
  extension="${path##*.}"
  classname=$(basename $path .java)

  git mv $filename.java $filename.kt
  git commit -m "Rename $classname"
  mv $filename.kt $filename.java
}

donecmd() {
  path=$1
  classname=$(basename $path .kt)

  git add -u $path
  git commit -m "Kotlinize $classname"
}

version() {
  echo "j2k v0.1"
}

case $1 in
checkout)
  checkout $2
  ;;
rename)
  rename $2
  ;;

done)
  donecmd $2
  ;;

version | --version | -v)
  version
  ;;
esac
